version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "csv2yaml"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1igy75j7zbyo6"
s3_prefix = "csv2yaml"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
