AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 Object Lambda

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled


  # Lambda function
  TransformFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: transform/
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Timeout: 60
      Policies: AWSLambdaExecute
      Events:
        CreateFileEvent:
          Type: S3
          Properties:
            Bucket: !Ref S3Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: suffix      # or "suffix"
                  Value: .csv      # The value to search for in the S3 object key names
                - Name: prefix      # or "suffix"
                  Value: approved/      # The value to search for in the S3 object ke
  PatcherFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: transform/
      Handler: patcher.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Timeout: 60
      Policies: 
        - AWSLambdaExecute
        - Statement:
          - Sid: SSMRunCommand
            Effect: Allow
            Action:
            - ssm:RunCommand
            - ssm:SendCommand
            Resource: '*'
      Events:
        CreateFileEvent:
          Type: S3
          Properties:
            Bucket: !Ref S3Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: suffix      # or "suffix"
                  Value: .yaml      # The value to search for in the S3 object key names
                - Name: prefix      # or "suffix"
                  Value: output/      # The value to search for in the S3 object ke

          
   
Outputs:
  S3Bucket:
    Value: !Ref S3Bucket
    Description: S3 Bucket for object storage.
  TransformFunction:
    Value: !Ref TransformFunction
    Description: TransformFunction ARN.
  PatcherFunction:
    Value: !Ref PatcherFunction
    Description: PatcherFunction ARN.